### ISSUE TITLE
DLURI has no value

### ISSUE THREAD

**Issue by dbhaigh** [enzo-g/azureIPranges#1]
This line does not work

$DLURI = $LocationURI.Links | Where-Object {$_.InnerText -Like "click here to download manually" }

However replacing it, and the line immediately above it 

"$LocationURI = Invoke-WebRequest -uri "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519"

With this line

( Invoke-WebREquest -Uri "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519").Links.Href | Where-Object { $_ -Like "*ServiceTags_Public*" } | Get-Unique

and you can get the download URI without error

Cheers

-=A=-

.

**Comment by enzo-g** [comment]
Hi @dbhaigh,

Thanks for your comment! I’ve marked the issue as closed as I’ve rewritten the script in Python.
Additionally, I’ve set up a GitHub Action to generate a GitHub Pages site that displays the JSON downloaded from Microsoft, along with all the TXT files generated using that JSON. Feel free to check it out here: https://enzo-g.github.io/azureIPranges/.

Cheers,
